# Generated by Django 4.2.1 on 2024-09-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='customer',
        ),
    ]
