# Generated by Django 4.2.1 on 2024-09-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Manager',
        ),
    ]
