# Generated by Django 4.2.1 on 2024-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('total_bonds', models.PositiveIntegerField(default=0)),
                ('avg_share_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('avg_bond_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
